### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [1]:
import numpy as np  # This is how to import numpy and assigning as np
A = np.array([1, 2, 3, 4, 5])  # initialize an array
print(A) # print the value of A
print("Shape:", A.shape) # print the size of each dimension of an array
print("Max:", A.max()) # print total value of elements in an array
print("Max using numpy:", np.max(A)) # print total value of elements in an array by using the function of numpy

[1 2 3 4 5]
Shape: (5,)
Max: 5
Max using numpy: 5


In [2]:
B = np.ones((5, 5), dtype=int) # B has a value of an  5X5 array with a data type of an integer all filled with ones
print(B) # print value of B
print(B.shape) # print the size of each dimension in the array B
print(B.size) # print the total size of the array B
print(np.ndim(B)) # print numbers of dimension in the array B

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(5, 5)
25
2


### Exercise

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [3]:
import numpy as np
A1 = np.arange(10, 70, 2) # created an array with 30 values within range of numbers given with an increment of 2

#print(A1) # print the A1 with just 30 values in it
#print(A1.size) # print the total size of the array

A2 = (A1 * 3) # Multiply the resulting array by 3
print(A2) # Print the result

[ 30  36  42  48  54  60  66  72  78  84  90  96 102 108 114 120 126 132
 138 144 150 156 162 168 174 180 186 192 198 204]


### Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


In [4]:
import numpy as np
array4D = np.random.randint(0, 13, size=(3, 4, 5, 6))
print(array4D) # Print the array
print(np.ndim(array4D)) # print the dimensions of the array using the function of numpy
print(array4D.shape) # print size of each dimension
print(array4D.size) # print the total size of the array

[[[[ 7 11 10  7  3  0]
   [ 3  8  0  3  7  0]
   [ 2  7  2  9 10  1]
   [ 3  9  2 12 11  7]
   [ 7  9  0 10  9  8]]

  [[ 4 11  2  3 10 10]
   [11  7 12 11  0  8]
   [12  5  0 10  7  9]
   [ 9  1 10  0  9  3]
   [10 10  6  6  0  9]]

  [[ 0  2  9  6  8 12]
   [ 2 11 10  0 11 11]
   [ 6  6  4  1  0  0]
   [ 2 12 10  6  3  7]
   [ 4  9  8  0  5  2]]

  [[ 5  4  5  5  2  6]
   [ 7  3  5  6  9 11]
   [11  8 12  0  9  2]
   [ 9 10  4  6  8  4]
   [ 0  8  5  6 12 11]]]


 [[[ 1  8  2  2 11  0]
   [ 9  9  9 12 11  8]
   [ 4  7  0  5  2  4]
   [ 3  4  7  4  6  2]
   [ 7  5  3 10  1  8]]

  [[ 6 12  1  5  9  7]
   [ 2  3  1  8 10  7]
   [ 0  6 10  0  7  1]
   [ 1  2  1  3  4  3]
   [10  8  7  8  6  9]]

  [[ 9  1  8  6  0  2]
   [ 5 12  2  8  0 11]
   [ 6  4  8  0  5 11]
   [ 5  8  1  6 11  4]
   [ 9  6  6 12 12 11]]

  [[ 8 10 12  0  8  7]
   [12 11  7  7  0  5]
   [11  9 10 10 10  4]
   [ 2  4  7 12 11  3]
   [ 8  7  6  2  2  4]]]


 [[[ 1  3 11  7  4  8]
   [12 10  9  9  3  5]
   [10  5  9  

In [5]:
max4D = np.max(array4D, axis=(0, 1, 2, 3)) # Using the function of numpy to get the maximum number for each dimensions
print(max4D) # Print the maximum number for each dimension

12


In [6]:
multiply4D = array4D * 4 # Multipy each array with 4
print(multiply4D) # Each element in the array4D is multiplied by 4, resulting in a new array where all values are four times larger than the original values.

[[[[28 44 40 28 12  0]
   [12 32  0 12 28  0]
   [ 8 28  8 36 40  4]
   [12 36  8 48 44 28]
   [28 36  0 40 36 32]]

  [[16 44  8 12 40 40]
   [44 28 48 44  0 32]
   [48 20  0 40 28 36]
   [36  4 40  0 36 12]
   [40 40 24 24  0 36]]

  [[ 0  8 36 24 32 48]
   [ 8 44 40  0 44 44]
   [24 24 16  4  0  0]
   [ 8 48 40 24 12 28]
   [16 36 32  0 20  8]]

  [[20 16 20 20  8 24]
   [28 12 20 24 36 44]
   [44 32 48  0 36  8]
   [36 40 16 24 32 16]
   [ 0 32 20 24 48 44]]]


 [[[ 4 32  8  8 44  0]
   [36 36 36 48 44 32]
   [16 28  0 20  8 16]
   [12 16 28 16 24  8]
   [28 20 12 40  4 32]]

  [[24 48  4 20 36 28]
   [ 8 12  4 32 40 28]
   [ 0 24 40  0 28  4]
   [ 4  8  4 12 16 12]
   [40 32 28 32 24 36]]

  [[36  4 32 24  0  8]
   [20 48  8 32  0 44]
   [24 16 32  0 20 44]
   [20 32  4 24 44 16]
   [36 24 24 48 48 44]]

  [[32 40 48  0 32 28]
   [48 44 28 28  0 20]
   [44 36 40 40 40 16]
   [ 8 16 28 48 44 12]
   [32 28 24  8  8 16]]]


 [[[ 4 12 44 28 16 32]
   [48 40 36 36 12 20]
   [40 20 36 1